// INCLUDING NECESSARY LIBRARIES TO TELL THE COMPILER WHICH FUNCTIONALITIES I WILL USE
#include <stdio.h>
#include <string.h>

// DEFINING CONSTANTS USING MACROS TO AVOID MAGIC NUMBERS AND MAKE THE CODE EASIER TO MODIFY IN THE FUTURE
#define MAX_DEVICES 5
#define ATTEMPTS 3
#define ID 100

// CREATING A FUNCTION TO CLEAR THE INPUT BUFFER AND PREVENT INFINITE LOOPS, REUSABLE WHENEVER I NEED IT
void clean_buffer(){
    int c;
    // LOOP THAT READS CHARACTERS UNTIL IT FINDS A NEWLINE OR THE END OF FILE (EOF)
    while ((c = getchar()) != '\n' && c != EOF);
}

// MAIN FUNCTION, WHERE THE PRINCIPAL CODE WILL BE HOUSED
// IT RETURNS AN INT TO INDICATE IF THE PROGRAM FINISHED SUCCESSFULLY (0) OR WITH ERRORS (1)
int main(){

    // VARIABLES AND ARRAYS DECLARATION. INITIALIZING VALUES LIKE THE CORRECT PASSWORD AND DEFAULT TRAFFIC RATES
    int password = 1234 , password_entered = 0 , password_attempts = 0;
    char id[ID];
    int ip_address[MAX_DEVICES] = {101, 102, 103, 104, 105};
    int traffic_rates[MAX_DEVICES] = {120, 680, 95, 820, 310};
    int opt , ip_count = 0;

    // ASKING FOR THE USERNAME
    printf("Enter your username: ");
    // USING FGETS FOR SAFER STRING HANDLING INSTEAD OF SCANF
    fgets(id , sizeof(id) , stdin);
    // USING STRCSPN TO FIND THE NEWLINE CHARACTER GENERATED BY FGETS AND REPLACING IT WITH A NULL TERMINATOR '\0'
    id[strcspn(id , "\n")] = '\0';

    // USING A DO-WHILE LOOP FOR AUTHENTICATION BECAUSE IT MUST ASK FOR THE PASSWORD AT LEAST ONCE
    do{
        printf("Enter your password: ");
        // INDICATING THAT IF SCANF FAILS TO READ AN INTEGER (RETURNS SOMETHING OTHER THAN 1)
        // IT IS BECAUSE THE USER ENTERED INVALID CHARACTERS LIKE LETTERS
        if(scanf("%d" , &password_entered)!= 1){
            password_attempts++;
            printf("ERROR: Enter a numeric value.\n");

            // CALLING THE FUNCTION TO CLEAR THE LEFTOVER CHARACTERS IN THE BUFFER SO SCANF DOESN'T GET STUCK
            clean_buffer();

            if (password == password_entered){
                continue;
            } 

            // IF THE USER REACHES THE MAXIMUM ALLOWED ATTEMPTS, WE BLOCK THE SYSTEM FOR SECURITY AND EXIT THE PROGRAM
            if (password_attempts == ATTEMPTS){
                printf("SYSTEM BLOCK\n");
                return 1;
            }

            // USING CONTINUE TO SKIP THE REST OF THE LOOP AND START THE NEXT ITERATION IMMEDIATELY
            continue;
        }

        // CLEARING THE BUFFER AGAIN JUST IN CASE EXTRA CHARACTERS WERE ENTERED AFTER THE NUMBER
        clean_buffer();

        // IF THE PASSWORD IS CORRECT, WE USE CONTINUE TO GO STRAIGHT TO THE CONDITION AND EXIT THE LOOP
        if (password == password_entered){
                continue;
            } else {
                // IF INCORRECT, WE ADD TO THE PASSWORD ATTEMPTS COUNTER
                password_attempts++;
            }

            // IF THE USER EXCEEDS THE MAXIMUM ATTEMPTS, THE SYSTEM LOCKS FOR SECURITY
            if (password_attempts == ATTEMPTS){
                printf("SYSTEM BLOCK\n");
                return 1;
            }
    } while (password != password_entered);

    printf("WELCOME.\n");

      // MAIN MENU LOOP. USING DO-WHILE SO THE USER SEES THE OPTIONS AT LEAST ONCE
      do{
        printf("=== MITIGADOR DDOS V1.0 ===\n");
        printf("1. View Network Traffic.\n");
        printf("2. Run DDos Mitigation.\n");
        printf("3. Reset Traffic Rates.\n");
        printf("4. Exit.\n");
        
        // CHECKING FOR INVALID INPUT (LETTERS INSTEAD OF NUMBERS) IN THE MENU SELECTION
        if(scanf("%d" , &opt)!=1){
            printf("ERROR: Enter a numeric value.\n");

            clean_buffer();
            opt = 0;
            continue;
        }
        
        clean_buffer();

        // USING A SWITCH STATEMENT TO HANDLE THE MENU OPTIONS BASED ON THE USER'S INPUT
        switch(opt){
            case 1:
                // FOR LOOP TO ITERATE THROUGH THE DEVICES ARRAY AND DISPLAY THEIR CURRENT NETWORK TRAFFIC
                for(int i = 0 ; i < MAX_DEVICES ; i++){
                    printf("IP Addrress: 192.168.1.%d | Traffic rates %dpps.\n" , ip_address[i] , traffic_rates[i]);
                }
            break;

            case 2: 
                // LOOP TO ANALYZE TRAFFIC RATES. IF AN IP EXCEEDS 500 PPS, IT IS CONSIDERED A DDOS ATTACK AND GETS MITIGATED
                for(int i = 0 ; i < MAX_DEVICES ; i++){
                    if(traffic_rates[i] > 500){
                        ip_count++;
                        printf("[ALERT] DDos Attack from IP: 192.168.1.%d. Mitigating %dpps.\n" , ip_address[i] , traffic_rates[i]);
                        // SETTING THE THREAT'S TRAFFIC BACK TO 0 TO MITIGATE IT
                        traffic_rates[i] = 0;
                    } else {
                        printf("[SAFE] IP: 192.168.1.%d\n" , ip_address[i]);
                    }
                }

                printf("Ip Mitigated: %d\n" , ip_count);
                break;

            case 3:
                // FOR LOOP TO RESET ALL TRAFFIC RATES BACK TO ZERO FOR ALL DEVICES
                for (int i = 0; i < MAX_DEVICES ; i++ ){
                    traffic_rates[i] = 0;
                }
                printf("[RESET] All Traffic rates reset to 0pps.\n");
                break;
                
            case 4:
                // EXITING THE PROGRAM.
                printf("Leaving the program...\n");
                break;

            default:
                // DEFAULT CASE TO CATCH ANY INVALID NUMERIC OPTION ENTERED BY THE USER
                printf("Invalid option.\n");
                break;
        }

    // THE MENU REPEATS WHILE THE OPTION IS DIFFERENT THAN 4
    }while(opt != 4);

    return 0;
}